apiVersion: apps/v1
kind: Deployment
metadata:
  name: bsoft-frontend-prod
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bsoft-frontend
      environment: prod
  template:
    metadata:
      labels:
        app: bsoft-frontend
        environment: prod
    spec:
      containers:
        - name: bsoft-frontend
          image: docker.io/bannarisoft/bsoft-frontend:latest
          ports:
            - containerPort: 80
          envFrom:
            # - configMapRef:
            #     name: frontend-env-prod
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5