apiVersion: apps/v1
kind: Deployment
metadata:
  name: bsoft-frontend-dev
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bsoft-frontend
      environment: dev
  template:
    metadata:
      labels:
        app: bsoft-frontend
        environment: dev
    spec:
      containers:
        - name: bsoft-frontend
          image: docker.io/bannarisoft/bsoft-frontend:dev
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: frontend-env-dev
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"