import "./globals.css";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import { ThemeProvider } from "../ThemeProviderWrapper";
import RecoilContextProvider from "../utils/RecoilContextProvider";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "BSOFT | Bannari Amman Spinning Mills Limited",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ThemeProvider>
      <html lang="en">
        <meta name="apple-mobile-web-app-title" content="MyWebSite" />
        <body>
          <RecoilContextProvider>{children}</RecoilContextProvider>
          <Toaster
            position="top-right"
            reverseOrder={false}
            toastOptions={{
              style: {
                background: "#333",
                color: "#fff",
                fontFamily: "Poppins, Arial, sans-serif",
                fontSize: "1rem",
              },
            }}
          />
        </body>
      </html>
    </ThemeProvider>
  );
}
