apiVersion: apps/v1
kind: Deployment
metadata:
  name: bsoft-frontend
  labels:
    app: bsoft-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bsoft-frontend
  template:
    metadata:
      labels:
        app: bsoft-frontend
    spec:
      containers:
        - name: bsoft-frontend
          image: ghcr.io/bannarisoft/bsoft-frontend:latest
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: bsoft-env
