apiVersion: v1
kind: Service
metadata:
  name: bsoft-frontend-service
spec:
  type: NodePort
  selector:
    app: bsoft-frontend
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080  # Access on http://<host-ip>:30080
